spring:
  datasource:
    url: jdbc:mysql://localhost/ticketmaster_db?createDatabaseIfNotExist=true
    username: root
    password : 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true